/*
What is the value of the first triangle number to have over five hundred
divisors?

The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
terms would be:
*/

package main

import (
    "fmt"
    "euler/primes"
)


func TriangleNumberFactors(nfactors uint64) (num uint64) {
    num = uint64(0) 
    for i:= uint64(1); primes.NumFactors(num)+uint64(1) < nfactors; num, i = num+i, i+uint64(1) {
    }
    return
}

func main() {
    fmt.Println(TriangleNumberFactors(500))
}
